### PR TITLE
Added smart comma separated notes, fixed gray pink

### LINKED ISSUE #2102: Note Pink & Gray Pink (6 Suits)
You cannot mark gray Pink with any letter, I tried them all

### PR DESCRIPTION
**Pull request by newduke**
First PR here.  I left the old code in and there is cruft. LMK if this needs changes. I can remove the old code.

#2028
#1801 
fixes #2102

### CODE REVIEW

File: client/src/game/reducers/noteIdentity.ts [hunk 1]
```diff
@@ -78,6 +170,9 @@ function getPossibilitiesFromKeyword(
   variant: Variant,
   keywordPreTrim: string,
 ): Array<[number, number]> | null {
+  if (1) {
```
Comment (newduke) [inline client/src/game/reducers/noteIdentity.ts:173]: Remove whole function

File: client/src/game/reducers/noteIdentity.ts [hunk 2]
```diff
@@ -191,6 +286,7 @@ export function createIdentityNotePattern(
   abbreviations: string[],
   isUpOrDown: boolean,
 ): string {
+  // debugger;
```
Comment (newduke) [inline client/src/game/reducers/noteIdentity.ts:289]: nix

File: client/src/game/reducers/noteIdentity.ts [hunk 3]
```diff
@@ -69,6 +69,98 @@ function possibilitiesComplement(
...
+}
+*/
+
+// Examines a single square bracket-enclosed part of a note (i.e. keyword) and returns the set of
+// card possibilities that it declares
+//
+// e.g. the note keyword `red` would return `[[0,1], [0,2], [0,3], [0,4], [0,5]]`
+// and the note keyword `red 3, blue 3` would return `[[0,3], [1,3]]`
+// and the note keyword `r,b,2,3, blue 3` would return `[[0,2], [1,2], [0,3], [1,3]]`
+// and the note keyword `r,!2,!3` would return `[[0,1], [0,4], [0,5]`
```
Comment (newduke) [inline client/src/game/reducers/noteIdentity.ts:107]: More examples

File: client/src/game/reducers/noteIdentity.ts (hunk 1 above)
Comment (Zamiell) [reply client/src/game/reducers/noteIdentity.ts:173]: if you dont want the function there, then comment it out, right?
or better yet just delete it entirely if the code isn't being used

File: client/src/game/reducers/noteIdentity.ts (hunk 2 above)
Comment (Zamiell) [reply client/src/game/reducers/noteIdentity.ts:289]: ?

**Comment by Zamiell** [comment]
the code fails the linter.
it feels like you probably dont have the linter installed... do you?

File: client/src/game/reducers/noteIdentity.ts [hunk 4]
```diff
@@ -47,91 +47,87 @@ export function parseIdentity(variant: Variant, keyword: string): CardIdentity {
...
+        possibilities.push([col, row + 1]);
       }
     }
   }
-
-  return complement;
+  return possibilities;
 }
 
-// Examines a single square bracket-enclosed part of a note (i.e. keyword) and returns the set of
```
Comment (Zamiell) [inline client/src/game/reducers/noteIdentity.ts:72]: why are you deleting this line

File: client/src/game/reducers/noteIdentity.ts [hunk 5]
```diff
@@ -47,91 +47,88 @@ export function parseIdentity(variant: Variant, keyword: string): CardIdentity {
...
-      for (let suitIndex = 0; suitIndex < variant.suits.length; suitIndex++) {
-        // Check that this identity is not already present in the list
-        if (
-          !possibilities.some(
-            (possibility) =>
-              possibility[0] === suitIndex && possibility[1] === identity.rank,
-          )
-        ) {
-          possibilities.push([suitIndex, identity.rank]);
+        for (let suitIndex = 0; suitIndex < variant.suits.length; ++suitIndex) {
```
Comment (Zamiell) [inline client/src/game/reducers/noteIdentity.ts:122]: suitIndex++

File: client/src/game/reducers/noteIdentity.ts [hunk 6]
```diff
@@ -47,91 +47,88 @@ export function parseIdentity(variant: Variant, keyword: string): CardIdentity {
...
+          if (identity.suitIndex !== null && identity.suitIndex !== suitIndex) {
+            continue;
```
Comment (Zamiell) [inline client/src/game/reducers/noteIdentity.ts:124]: instead of using a continue statement, invert the conditional and stick the line inside

File: client/src/game/reducers/noteIdentity.ts (hunk 2 above)
Comment (Zamiell) [reply client/src/game/reducers/noteIdentity.ts:191]: what is this line

**Comment by Zamiell** [comment]
```
// e.g. the note keyword `red` would return `[[0,1], [0,2], [0,3], [0,4], [0,5]]`
// and the note keyword `red 3, blue 3` would return `[[0,3], [1,3]]`
// and the note keyword `r,b,2,3, blue 3` would return `[[0,2], [1,2], [0,3], [1,3]]`
// and the note keyword `r,!2,!3` would return `[[0,1], [0,4], [0,5]`
```
can you make tests for these 4 examples

File: client/src/game/reducers/noteIdentity.ts (hunk 6 above)
Comment (newduke) [reply client/src/game/reducers/noteIdentity.ts:124]: I like `continue` because it means less nesting, so IMHO lower (visual) complexity.

Comment (Zamiell) [reply client/src/game/reducers/noteIdentity.ts:124]: i dont understand how it results in less nesting.
the cyclomatic complexity of the function is the same.

File: client/src/game/reducers/noteIdentity.ts [hunk 7]
```diff
@@ -47,91 +47,88 @@ export function parseIdentity(variant: Variant, keyword: string): CardIdentity {
...
-      ) {
-        complement.push([suitIndex, rank]);
+function identityMapToArray(cardMap: number[][]): Array<[number, number]> {
+  const rows = cardMap.length;
+  const cols = cardMap[0].length;
+  const possibilities: Array<[number, number]> = [];
+  for (let row = 0; row < rows; ++row) {
+    for (let col = 0; col < cols; ++col) {
+      if (cardMap[row][col]) {
+        possibilities.push([col, row + 1]);
```
Comment (timotree3) [inline client/src/game/reducers/noteIdentity.ts:57]: We typically use the words `rank` and `suitIndex` in this kind of scenario

File: client/src/game/reducers/noteIdentity.ts [hunk 8]
```diff
@@ -47,91 +47,88 @@ export function parseIdentity(variant: Variant, keyword: string): CardIdentity {
...
-  return complement;
+  return possibilities;
 }
 
 // Examines a single square bracket-enclosed part of a note (i.e. keyword) and returns the set of
 // card possibilities that it declares
 //
 // e.g. the note keyword `red` would return `[[0,1], [0,2], [0,3], [0,4], [0,5]]`
 // and the note keyword `red 3, blue 3` would return `[[0,3], [1,3]]`
+// and the note keyword `r,b,2,3, blue 3` would return `[[0,2], [1,2], [0,3], [1,3]]`
```
Comment (timotree3) [inline client/src/game/reducers/noteIdentity.ts:69]: I find this surprising. It makes more sense to me that `r,b,2,3` means the union of all red cards + all blue cards + all 2's + all 3's. `[r,b] [2,3]` would mean to me what you describe.

Comment (timotree3) [reply client/src/game/reducers/noteIdentity.ts:69]: (The behavior I'm describing is what it did before. )

File: client/src/game/reducers/noteIdentity.ts [hunk 9]
```diff
@@ -47,91 +47,88 @@ export function parseIdentity(variant: Variant, keyword: string): CardIdentity {
...
+  const positiveIdent = [];
+  const negativeIdent = [];
+  let positiveRanks = new Set<number>();
+  let positiveSuits = new Set<number>();
+  for (const substring of keywordPreTrim.split(",")) {
+    const trimmed = substring.trim();
+    const negative = trimmed.startsWith("!");
+    const identity = parseIdentity(
+      variant,
+      (negative ? trimmed.substring(1) : trimmed).trim(),
```
Comment (timotree3) [inline client/src/game/reducers/noteIdentity.ts:84]: This extra `.trim()` means that there can be whitespace between the `!` and its operand. Is that desirable?

**Review by timotree3 — COMMENTED** [review]
Hey newduke! It's been a while. Thanks for putting the time into making this PR! I have a concern about the overall behavior of this new design that I left below.

File: client/src/game/reducers/noteIdentity.ts (hunk 9 above)
Comment (newduke) [reply client/src/game/reducers/noteIdentity.ts:84]: Yes, that is the intent.

File: client/src/game/reducers/noteIdentity.ts (hunk 8 above)
Comment (newduke) [reply client/src/game/reducers/noteIdentity.ts]: you can still do `[r,b] [2,3]` but this way you don't need the brackets. The OR interpretation doesn't really make sense, IMHO. Who would ever want to mark a card like such?

File: client/src/game/reducers/noteIdentity.ts [hunk 10]
```diff
@@ -65,17 +65,17 @@ function identityMapToArray(cardMap: number[][]): Array<[number, number]> {
...
 // and the note keyword `r,!2,!3` would return `[[0,1], [0,4], [0,5]`
 function getPossibilitiesFromKeyword(
   variant: Variant,
   keywordPreTrim: string,
 ): Array<[number, number]> | null {
-  const positiveIdent = [];
-  const negativeIdent = [];
-  let positiveRanks = new Set<number>();
-  let positiveSuits = new Set<number>();
+  const positiveIdent = []; // single cards `r1` `b3`
```
Comment (Zamiell) [inline client/src/game/reducers/noteIdentity.ts:73]: all comments must be capitalized

File: client/src/game/reducers/noteIdentity.ts [hunk 11]
```diff
@@ -98,15 +99,20 @@ function getPossibilitiesFromKeyword(
   }
   // Start with the cross of the positive ranks and suits.
   const hasSuits = positiveSuits.size > 0;
+  const hasRanks = positiveRanks.size > 0;
+  const hasPositives = hasSuits || hasRanks || positiveIdent.length > 0;
   if (!positiveSuits.size) positiveSuits = new Set([0, 1, 2, 3, 4, 5]);
-  if (hasSuits && !positiveRanks.size) positiveRanks = new Set([1, 2, 3, 4, 5]);
+  console.log(positiveSuits);
+  if (!hasPositives || (hasSuits && !hasRanks))
```
Comment (Zamiell) [inline client/src/game/reducers/noteIdentity.ts:103]: always use opening braces for if statements

File: client/src/game/reducers/noteIdentity.ts [hunk 12]
```diff
@@ -50,9 +50,9 @@ export function parseIdentity(variant: Variant, keyword: string): CardIdentity {
 function identityMapToArray(cardMap: number[][]): Array<[number, number]> {
   const possibilities: Array<[number, number]> = [];
   for (let rank = 1; rank <= cardMap.length; ++rank) {
-    for (let suit = 0; suit < cardMap[0].length; ++suit) {
-      if (cardMap[rank - 1][suit]) {
-        possibilities.push([suit, rank]);
+    for (let suitIndex = 0; suitIndex < cardMap[0].length; ++suitIndex) {
```
Comment (Zamiell) [inline client/src/game/reducers/noteIdentity.ts:53]: wrong ++

**Comment by newduke** [comment]
> ```
> // e.g. the note keyword `red` would return `[[0,1], [0,2], [0,3], [0,4], [0,5]]`
> // and the note keyword `red 3, blue 3` would return `[[0,3], [1,3]]`
> // and the note keyword `r,b,2,3, blue 3` would return `[[0,2], [1,2], [0,3], [1,3]]`
> // and the note keyword `r,!2,!3` would return `[[0,1], [0,4], [0,5]`
> ```
> 
> can you make tests for these 4 examples

Done

File: client/src/game/reducers/noteIdentity.ts (hunk 8 above)
Comment (timotree3) [reply client/src/game/reducers/noteIdentity.ts]: Consider the following scenario in a 3-player game
- Red 2 and Green 2 are on on the stacks
- Cathy has a green 3 on finesse position.
- Bob has three unclued cards.
- Alice clues blue to Cathy touching an already fully known blue 3
- Bob blind-plays red 3 from Finesse Position and realizes it's a 3 bluff.
- Cathy discards.
- Now Bob is sad because green 1 left finesse position. If Alice had just clued him directly on the red 3, then Bob could've bluffed the green 1.
- Bob realizes that if nobody made a mistake, then Alice must not have been able to clue the red 3 directly, therefore he has a red card or a 2 on chop, and a trash red card or a trash 2 in second finesse position.
- Bob writes the note `r,2` on his chop, and it turns into a picture of the red 2
- Bob wishes that this change to note behavior was not made

Comment (Zamiell) [reply client/src/game/reducers/noteIdentity.ts]: that seems pretty contrived

Comment (Zamiell) [reply client/src/game/reducers/noteIdentity.ts]: but yes, `r, 3` naturally should represent red or 3.
the fact that it doesn't is just a consequence of your change to remove comma parsing, so it seems like your fault if anything

Comment (timotree3) [reply client/src/game/reducers/noteIdentity.ts]: 3-player Rainbow game:
- Red 5 and rainbow 3 are on that stacks
- Two copies of rainbow 1 and one copy of rainbow 2 are in the discard pile
- Alice clues red to Cathy
- Bob discharges
- Cathy knows that this is a trash card, so writes the note `[red, 3] [kt]`
- The card morphs into a red 3 much to Cathy's dismay

File: client/src/game/reducers/noteIdentity.test.ts [hunk 13]
```diff
@@ -0,0 +1,77 @@
...
+      const possibles = getPossibilitiesFromKeywords(testVariant, ["red"]);
+      expect(possibles).toEqual([
+        [0, 1],
+        [0, 2],
+        [0, 3],
+        [0, 4],
+        [0, 5],
+      ]);
+    });
+    // and the note keyword `red 3, blue 3` would return `[[0,3], [1,3]]`
```
Comment (Zamiell) [inline client/src/game/reducers/noteIdentity.test.ts:42]: put a newline between tests

File: client/src/game/reducers/noteIdentity.ts (hunk 8 above)
Comment (newduke) [reply client/src/game/reducers/noteIdentity.ts]: so... what is the consensus here?  r,3= red OR 3?

Comment (Zamiell) [reply client/src/game/reducers/noteIdentity.ts]: i was gonna wait for timo to respond

Comment (Zamiell) [reply client/src/game/reducers/noteIdentity.ts]: to my 2nd comment, not my 1st comment

Comment (timotree3) [reply client/src/game/reducers/noteIdentity.ts]: > but yes, `r, 3` naturally should represent red or 3.
> the fact that it doesn't is just a consequence of your change to remove comma parsing (maybe?), so it seems like your fault if anything

You mean it's my fault? I don't think I removed comma parsing

Comment (timotree3) [reply client/src/game/reducers/noteIdentity.ts]: > so... what is the consensus here? r,3= red OR 3?

That's where I'm at

Comment (Zamiell) [reply client/src/game/reducers/noteIdentity.ts]: i thought your change was to make `r, b` === `rb`

Comment (timotree3) [reply client/src/game/reducers/noteIdentity.ts]: You mean shorthand like `rb3` means `r3,b3`? I never implemented that

Comment (Zamiell) [reply client/src/game/reducers/noteIdentity.ts]: anyways, back on topic, yes i think whatever system that we come up with, a note of `r, 3` must not transform the card into a red 3

Comment (Zamiell) [reply client/src/game/reducers/noteIdentity.ts]: iirc timo smartly suggested previous that multiple suits were ANDed to gether, and multiple ranks were ANDed together, and then the suits+ranks are ORed together

Comment (timotree3) [reply client/src/game/reducers/noteIdentity.ts]: I don't think that makes sense. A card can't be red AND blue

Comment (Zamiell) [reply client/src/game/reducers/noteIdentity.ts]: youre right, what suggestion am i thinking of

Comment (Zamiell) [reply client/src/game/reducers/noteIdentity.ts]: oh i think i was thinking of this https://github.com/Zamiell/hanabi-live/pull/2028#issuecomment-770447023

Comment (Zamiell) [reply client/src/game/reducers/noteIdentity.ts]: maybe its not relevant since the squishing code isn't implemented yet

**Comment by Zamiell** [comment]
is the r, 3 thing fixed?

File: client/src/game/reducers/noteIdentity.test.ts [hunk 14]
```diff
@@ -39,6 +39,7 @@ describe("noteIdentity", () => {
         [0, 5],
       ]);
     });
+
     // and the note keyword `red 3, blue 3` would return `[[0,3], [1,3]]`
```
Comment (Zamiell) [inline client/src/game/reducers/noteIdentity.test.ts:43]: all comments must be capitalized

File: client/src/game/reducers/noteIdentity.ts (hunk 8 above)
Comment (newduke) [reply client/src/game/reducers/noteIdentity.ts]: Ok, I implemented squish notes which should make everyone happy. So now `[b,r][2,3] === rb23` and `r3 !== r,3` but rather `r,3` is red OR 3.  Squish notation pretty much covers all abbreviations, but I left in the old regex as legacy.

**Comment by Zamiell** [comment]
cool lets try it out!
