### PR TITLE
discord: Fix nickname behavior and improve approach to Guild Member and Channel resolution

### LINKED ISSUE #1653: When Discord messages get replicated in the lobby, the usernames in @-mentions do not match Discord.
For example, in Discord:
Discord Mention

Replicated to lobby:
Lobby Mention

The desired behavior would be to put the server-wide discord nickname of the mentioned user in the lobby, not their discord username.

### PR DESCRIPTION
**Pull request by timotree3**
Fixes #1653

### CODE REVIEW

**Comment by timotree3** [comment]
We no longer ever query for a Guild object. Therefore the code that refreshes our cache of them was deleted.

File: server/src/discord.go [hunk 1]
```diff
@@ -194,61 +176,23 @@ func discordGetNickname(discordID string) string {
...
-	}
 }
 
 func discordGetChannel(discordID string) string {
-	// Get the Discord guild object
-	var guild *discordgo.Guild
-	if v, err := discord.Guild(discordListenChannels[0]); err != nil {
+	if channel, err := discord.Channel(discordID); err != nil {
 		// This can occasionally fail, so we don't want to report the error to Sentry
 		logger.Info("Failed to get the Discord guild:", err)
```
Comment (padiwik) [inline server/src/discord.go:191]: failed to get the Discord channel now
