### PR TITLE
[client] allow < & > " in notes by using HTML entities

### LINKED ISSUE #2149: Notes: left angle bracket causes deletion of partial note
Steps to reproduce
1. Start writing a note
2. Write `hello <world`
3. Press enter
4. Look at the note
5. It contains `hello `

### PR DESCRIPTION
**Pull request by DrAnax**
Fixes #2149

### CODE REVIEW

File: client/src/game/ui/notes.ts [hunk 1]
```diff
@@ -170,9 +170,9 @@ export function openEditTooltip(card: HanabiCard): void {
         );
       }
 
-      // Strip any HTML elements
+      // Convert &, <, >, " to HTML entities
       // (to be thorough, the server will also perform this validation)
```
Comment (timotree3) [inline client/src/game/ui/notes.ts:174]: This comment is now out of date right?
```suggestion
      // Convert &, <, >, " to HTML entities
      // (to be thorough, the server will also validate that it contains no HTML tags)
```

**Review by timotree3 — COMMENTED** [review]
That was fast! Thanks for fixing this

**Comment by Zamiell** [comment]
i'd prefer if you also did it on more characters
how about single quote, forward slash, both of those are used in xss attacks

File: client/src/game/ui/notes.ts [hunk 2]
```diff
@@ -219,7 +219,10 @@ export function setAllCardIndicators(): void {
...
 
-function stripHTMLTags(input: string) {
-  const doc = new DOMParser().parseFromString(input, "text/html");
-  return doc.body.textContent ?? "";
+function convertHTMLEntities(input: string) {
+  return String(input)
+    .replace(/&/g, "&amp;")
+    .replace(/</g, "&lt;")
+    .replace(/>/g, "&gt;")
+    .replace(/"/g, "&quot;");
```
Comment (timotree3) [inline client/src/game/ui/notes.ts:227]: If you want to make this really robust it might make sense just to try putting the contents inside of a `p` and see how to browser escapes it. I tested that this works on Firefox.
```suggestion
function convertHTMLEntities(input: string) {
  const p = document.createElement("p");
  p.appendChild(document.createTextNode(input))
  return p.innerHTML
```

At that point I wonder why we don't just remove all this logic and do it where we're displaying the notes instead

Comment (Zamiell) [reply client/src/game/ui/notes.ts]: is that safe

Comment (timotree3) [reply client/src/game/ui/notes.ts]: why wouldn't it be? It doesn't interpret the text passed to `createTextNode` as HTML

Comment (DrAnax) [reply client/src/game/ui/notes.ts]: It only converts &, <, >

Comment (Zamiell) [reply client/src/game/ui/notes.ts]: https://stackoverflow.com/questions/6234773/can-i-escape-html-special-chars-in-javascript

anax is this where you found the code?

Comment (Zamiell) [reply client/src/game/ui/notes.ts]: its probably safer to use jquery's test function.
its an antipattern to roll your own security

Comment (DrAnax) [reply client/src/game/ui/notes.ts]: > https://stackoverflow.com/questions/6234773/can-i-escape-html-special-chars-in-javascript
> 
> anax is this where you found the code?

Nope, just wrote it

Comment (DrAnax) [reply client/src/game/ui/notes.ts]: > its probably safer to use jquery's text function.
> its an antipattern to roll your own security

Can't use text() on an input element

Comment (Zamiell) [reply client/src/game/ui/notes.ts]: can't you use it as a replacement for the function that you hand-crafted?

Comment (DrAnax) [reply client/src/game/ui/notes.ts]: I can create a new element, paste the input's value and get it back via the text() function, is this ok?

Comment (Zamiell) [reply client/src/game/ui/notes.ts]: oh, i guess that is pretty similar to what tim is proposing

Comment (DrAnax) [reply client/src/game/ui/notes.ts]: So, use this?

function convertHTMLEntities(input: string) {
  const p = document.createElement("p");
  p.appendChild(document.createTextNode(input))
  return p.innerHTML

Comment (Zamiell) [reply client/src/game/ui/notes.ts]: ok i looked it up and jquery's text() function just does the code that tim suggested, so let's go with tim's code instead

Comment (Zamiell) [reply client/src/game/ui/notes.ts]: also, i am talking to you on discord, but you are not online =p

**Comment by Zamiell** [comment]
nice work
