### PR TITLE
Fix BGA nameframes

### LINKED ISSUE #1331: Nameframes look broken with one extra card or one less card

### PR DESCRIPTION
**Pull request by padiwik**
* No changes to the current UI for standard options
* Fix #1331 , at least in BGA mode. Keldon hands might look weird with one less card, but there isn't really a good way to fix that.

### CODE REVIEW

File: client/src/game/ui/drawHands.ts [hunk 1]
```diff
@@ -107,26 +115,6 @@ export default function drawHands(winW: number, winH: number) {
...
-  for (let j = 0; j < 4; j++) {
-    handPosBGA[4].push({
-      x: handPosBGAValues4.x,
-      y: handPosBGAValues4.y + (handPosBGAValues4.spacing * j),
-      w: handPosBGAValues4.w,
-      h: handPosBGAValues4.h,
-      rot: 0,
-    });
-  }
-
```
Comment (padiwik) [inline client/src/game/ui/drawHands.ts:129]: lol this part was leftover from the BGA prototype years ago, but it doesn't do anything since it pushes to an array that's already populated

**Comment by Zamiell** [comment]
status: padi is going to try to simplify the code further and will do another commit

**Comment by padiwik** [comment]
id appreciate merging this now, will be easier

**Comment by Zamiell** [comment]
ok
